[package]
name = "arnold_decoder"
authors = ["Aristore"]
version = "2.0.0"
edition = "2024"

[dependencies]
image = "0.24"
rayon = "1.6"
indicatif = { version = "0.17", features = ["rayon"] }
anyhow = "1.0" 